delete from SubTasks
delete from TaskItemStatusHistory
delete from TaskWithinList
delete from TaskItemNotes
delete from Lists
delete from TaskItems
delete from Statuses
delete from Users
delete from Password
delete from DeviceData
delete from Profile
delete from Address
delete from PurposeTypes
delete from LicenseTypes
