USE [master]
GO

/****** Object:  Database [TaskManagerApp]    Script Date: 10/2/2025 1:03:48 AM ******/
CREATE DATABASE [TaskManagerApp]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaskManagerApp', FILENAME = N'C:\Users\< UserName_Here >\TaskManagerApp.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaskManagerApp_log', FILENAME = N'C:\Users\< UserName_Here >\TaskManagerApp_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaskManagerApp].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [TaskManagerApp] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [TaskManagerApp] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [TaskManagerApp] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [TaskManagerApp] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [TaskManagerApp] SET ARITHABORT OFF 
GO

ALTER DATABASE [TaskManagerApp] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [TaskManagerApp] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [TaskManagerApp] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [TaskManagerApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [TaskManagerApp] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [TaskManagerApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [TaskManagerApp] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [TaskManagerApp] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [TaskManagerApp] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [TaskManagerApp] SET  DISABLE_BROKER 
GO

ALTER DATABASE [TaskManagerApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [TaskManagerApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [TaskManagerApp] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [TaskManagerApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [TaskManagerApp] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [TaskManagerApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [TaskManagerApp] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [TaskManagerApp] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [TaskManagerApp] SET  MULTI_USER 
GO

ALTER DATABASE [TaskManagerApp] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [TaskManagerApp] SET DB_CHAINING OFF 
GO

ALTER DATABASE [TaskManagerApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [TaskManagerApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [TaskManagerApp] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [TaskManagerApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [TaskManagerApp] SET QUERY_STORE = OFF
GO

ALTER DATABASE [TaskManagerApp] SET  READ_WRITE 
GO


